from gofra.exceptions import GofraError


class LexerError(GofraError): ...


class LexerEmptyInputLinesError(LexerError): ...


class LexerStringTokenError(LexerError): ...


class LexerUnclosedStringQuoteError(LexerError): ...


class LexerSymbolTokenError(LexerError): ...


class LexerUnclosedSymbolQuoteError(LexerSymbolTokenError): ...


class LexerEmptySymbolError(LexerSymbolTokenError): ...


class LexerAmbiguousSymbolLengthError(LexerSymbolTokenError): ...
