# This file is auto-generated by MSPL python subcommand! 

# Allocate stack (As is MSPL is Stack-Oriented Language): 
stack = list()

# Work with stack functions: 
def push(v):
	stack.append(v)
def pop():
	return stack.pop()


# Source (if_example.mspl): 
push(0)  # Text: 0 [Line 4, Row 1]

if pop() != 0:  # Text: if [Line 4, Row 3]
	push(1024)  # Text: 1024 [Line 8, Row 5]

	print(pop())  # Text: show [Line 8, Row 10]
push(1)  # Text: 1 [Line 11, Row 1]

if pop() != 0:  # Text: if [Line 11, Row 3]
	push(2048)  # Text: 2048 [Line 16, Row 5]

	print(pop())  # Text: show [Line 16, Row 10]
push(1)  # Text: 1 [Line 19, Row 1]

if pop() != 0:  # Text: if [Line 19, Row 3]
	push(1)  # Text: 1 [Line 19, Row 6]

	if pop() != 0:  # Text: if [Line 19, Row 8]
		push(4096)  # Text: 4096 [Line 23, Row 5]

		print(pop())  # Text: show [Line 23, Row 10]
